config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  resources :inventory_foods
  resources :inventories
  resources :recipes
  resources :foods
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


  # Defines the root path route ("/")
  root to: 'public_recipes#index', as: 'public_recipes'
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food

  validates :quantity, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
  validates :inventory, presence: true
  validates :food, presence: true
  validates :food, uniqueness: { scope: :inventory }
end

app/controllers/inventory_foods_controller.rb
class InventoryFoodsController < ApplicationController
  before_action :set_inventory_food, only: %i[ show edit update destroy ]

  # GET /inventory_foods or /inventory_foods.json
  def index
    @inventory_foods = InventoryFood.all
  end

  # GET /inventory_foods/1 or /inventory_foods/1.json
  def show
  end

  # GET /inventory_foods/new
  def new
    @inventory_food = InventoryFood.new
  end

  # GET /inventory_foods/1/edit
  def edit
  end

  # POST /inventory_foods or /inventory_foods.json
  def create
    @inventory_food = InventoryFood.new(inventory_food_params)

    respond_to do |format|
      if @inventory_food.save
        format.html { redirect_to inventory_food_url(@inventory_food), notice: "Inventory food was successfully created." }
        format.json { render :show, status: :created, location: @inventory_food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_foods/1 or /inventory_foods/1.json
  def update
    respond_to do |format|
      if @inventory_food.update(inventory_food_params)
        format.html { redirect_to inventory_food_url(@inventory_food), notice: "Inventory food was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory_food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_foods/1 or /inventory_foods/1.json
  def destroy
    @inventory_food.destroy

    respond_to do |format|
      format.html { redirect_to inventory_foods_url, notice: "Inventory food was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_food
      @inventory_food = InventoryFood.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_food_params
      params.require(:inventory_food).permit(:quantity, :inventory_id, :food_id)
    end
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/views/inventory_foods/_form.html.erb
<%= form_with(model: inventory_food) do |form| %>
  <% if inventory_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory_food.errors.count, "error") %> prohibited this inventory_food from being saved:</h2>

      <ul>
        <% inventory_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %>
  </div>

  <div>
    <%= form.label :inventory_id, style: "display: block" %>
    <%= form.text_field :inventory_id %>
  </div>

  <div>
    <%= form.label :food_id, style: "display: block" %>
    <%= form.text_field :food_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inventory_foods/_inventory_food.html.erb
<div id="<%= dom_id inventory_food %>">
  <p>
    <strong>Quantity:</strong>
    <%= inventory_food.quantity %>
  </p>

  <p>
    <strong>Inventory:</strong>
    <%= inventory_food.inventory_id %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= inventory_food.food_id %>
  </p>

</div>

app/views/inventory_foods/edit.html.erb
<h1>Editing inventory food</h1>

<%= render "form", inventory_food: @inventory_food %>

<br>

<div>
  <%= link_to "Show this inventory food", @inventory_food %> |
  <%= link_to "Back to inventory foods", inventory_foods_path %>
</div>

app/views/inventory_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inventory foods</h1>

<div id="inventory_foods">
  <% @inventory_foods.each do |inventory_food| %>
    <%= render inventory_food %>
    <p>
      <%= link_to "Show this inventory food", inventory_food %>
    </p>
  <% end %>
</div>

<%= link_to "New inventory food", new_inventory_food_path %>

app/views/inventory_foods/new.html.erb
<h1>New inventory food</h1>

<%= render "form", inventory_food: @inventory_food %>

<br>

<div>
  <%= link_to "Back to inventory foods", inventory_foods_path %>
</div>

app/views/inventory_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inventory_food %>

<div>
  <%= link_to "Edit this inventory food", edit_inventory_food_path(@inventory_food) %> |
  <%= link_to "Back to inventory foods", inventory_foods_path %>

  <%= button_to "Destroy this inventory food", @inventory_food, method: :delete %>
</div>